name: noaa
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - bottleneck
  - dask
  - fiona
  - ipykernel
  - jupyter
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - xarray
  - shapely
  - descartes
  - geopandas
  - regionmask
  - scipy
  - seaborn
  - scikit-learn
  - pip:
    - datetime
    - rasterio
    - cartopy
    - statsmodels
    - h5py
