name: noaa2
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - dask
  - fiona
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - xarray
  - shapely
  - descartes
  - geopandas
  - regionmask
  - scipy
  - seaborn
  - pip:
    - netCDF4
    - datetime
    - rasterio
